default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.dig(:database, :host) %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) || 'pleitrust@123' %>
  port: <%= Rails.application.credentials.dig(:database, :port) %>

development:
  <<: *default
  database: plei_trust_development

test:
  <<: *default
  database: plei_trust_test

production:
  <<: *default
  database: plei_trust_production
